# Generated by Django 4.0.5 on 2023-02-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userdata_username_userdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
