# Generated by Django 4.0.5 on 2023-03-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemshop',
            name='image',
            field=models.ImageField(null=True, upload_to='items/'),
        ),
    ]
