# Generated by Django 4.0.5 on 2023-03-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemShop',
            new_name='Product',
        ),
    ]
