# Generated by Django 4.0.5 on 2023-03-31 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cart_id_alter_favorite_id_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
